### ISSUE TITLE
processFulltextAssetDocument is not working while processFulltextDocument works fine

### ISSUE THREAD

**Issue by officialsuyogdixit** [eLifePathways/sciencebeam-parser#468]
**I am trying to convert PDF to JATS XML with Assets in zip.**

**500 Internal Server Error is thrown by latest sciencebeam docker when we try to process PDFs by processFulltextAssetDocument API.** 

I am using this command to run my docker:
docker run --rm -p 8070:8070 elifesciences/sciencebeam-parser
I have also tried it with Computer Vision via this command:
docker run --rm -p 8070:8070 --env SCIENCEBEAM_PARSER__PROCESSORS__FULLTEXT__USE_CV_MODEL=true --env SCIENCEBEAM_PARSER__PROCESSORS__FULLTEXT__USE_OCR_MODEL=true elifesciences/sciencebeam-parser:latest-cv

Note:
processFulltextDocument works fine or convert API just works fine.
I have also already tried it with multiple sample PDFs like https://www.apa.org/pubs/journals/features/edu-edu0000214.pdf 

I am sending this command via cURL:
curl --fail --show-error --header 'Accept: application/vnd.jats+xml+zip' --output "test.zip" --form "file=@/Users/mymacbookusername/Downloads/sample.pdf;filename=sample.pdf" --silent "http://localhost:8070/api/processFulltextAssetDocument?first_page=2"

Here is trackback:
[2021-11-23 10:29:35,329] INFO in sciencebeam_parser.document.tei_document:164: generating tei document done, took: front: 0.008415s, body: 0.617844s, back: 0.455715s, total: 1.081975s
[2021-11-23 10:29:35,336] INFO in sciencebeam_parser.app.parser:286: tei to jats, took=0.007s
[2021-11-23 10:29:35,337] INFO in sciencebeam_parser.app.parser:297: serializing xml, took=0.001s
[2021-11-23 10:29:35,347] ERROR in server:1458: Exception on /api/processFulltextAssetDocument [POST]
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/sciencebeam_parser/sciencebeam_parser/service/blueprints/api.py", line 760, in process_pdf_to_tei_assets_zip
    fulltext_processor_config=self.fulltext_processor_config
  File "/opt/sciencebeam_parser/sciencebeam_parser/service/blueprints/api.py", line 701, in _process_pdf_to_response_media_type
    response_media_type
  File "/opt/sciencebeam_parser/sciencebeam_parser/app/parser.py", line 496, in get_local_file_for_response_media_type
    response_media_type
  File "/opt/sciencebeam_parser/sciencebeam_parser/app/parser.py", line 393, in get_local_file_for_response_media_type
    response_media_type
  File "/opt/sciencebeam_parser/sciencebeam_parser/app/parser.py", line 331, in get_local_file_for_response_media_type
    relative_xml_filename=relative_xml_filename
  File "/opt/sciencebeam_parser/sciencebeam_parser/app/parser.py", line 114, in create_asset_zip_for_semantic_document
    assert semantic_graphic.relative_path
AssertionError
[2021-11-23 10:29:35,348] INFO in werkzeug:225: 172.17.0.1 - - [23/Nov/2021 10:29:35] "POST /api/processFulltextAssetDocument?first_page=2 HTTP/1.1" 500 -

**Comment by de-code** [comment]
Hi @suyogricha thank you for raising the issue. Unfortunately this issue doesn't seem to have been caught by the test coverage.
It should now be fixed in [v0.1.5](https://github.com/elifesciences/sciencebeam-parser/releases/tag/v0.1.5).

You could run `docker pull elifesciences/sciencebeam-parser` or use the `0.1.5` tag to ensure that you use the latest Docker image. (I would generally recommend using specific tags)

Please test again and close the issue if you feel that the issue is resolved.

**Comment by de-code** [comment]
Hi @suyogricha can this issue be closed?

**Comment by de-code** [comment]
Closing as it seems to be fixed. Please let me know if you think it isn't.
